spring:
  profiles:
    active: dev
  data:
    elasticsearch:
      repositories:
        enabled: false

management:
  health:
    elasticsearch:
      enabled: false
    rabbit:
      enabled: false
